# -*- coding: utf-8 -*-
"""rtdetr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rld3MQ87DXw_Jkf3_Neex1xOAncDO6Gb
"""

import os, json, random, shutil
from pathlib import Path
from collections import Counter, defaultdict
from PIL import Image

# PORTED 2026-08-26 (pcb-port-to-batch): Kaggle path block replaced by hpc_env.py.
from hpc_env import COCO_JSON, IMG_ROOT, NEG_ROOT, RUNS_ROOT, WORK, weights, devices

INPUT_ROOT = None                 # unused off-Kaggle; kept so auto-discovery branches stay dead
YOUR_COCO_JSON = str(COCO_JSON)
YOUR_IMG_ROOT  = str(IMG_ROOT)
NEG_IMG_ROOT   = str(NEG_ROOT)

KEEP = ["Component Liftup","Component Missing","Component No Solder",
        "Component Solder Dry","Polarity Wrong","RYB Wrong Sequence",
        "Solder Ball","Solder Short"]

# RT-DETR model (Ultralytics). rtdetr-l = large; rtdetr-x = extra-large.
MODEL       = weights("rtdetr-l.pt")   # staged path if offline/weights/ has it, else bare name
IMG_SIZE    = 640
BATCH       = int(os.environ.get("PCB_BATCH", 8))    # RT-DETR is heavier than YOLO; 8 is T4-safe. Lower to 4 if OOM.
EPOCHS      = int(os.environ.get("PCB_EPOCHS", 150)) # PCB_EPOCHS=2 for a smoke test
SEED        = 42
VAL_FRAC    = 0.20
N_NEG_TOTAL = 150

IMAGE_EXTS = [".jpg",".jpeg",".png",".bmp",".JPG",".JPEG",".PNG",".BMP"]
random.seed(SEED)

def coco_bbox_to_yolo(b,W,H):
    x,y,w,h=b
    return (x+w/2)/W,(y+h/2)/H,w/W,h/H

def write_yolo_split(coco, ids, split, out_root, src_lookup, names):
    (out_root/f"images/{split}").mkdir(parents=True,exist_ok=True)
    (out_root/f"labels/{split}").mkdir(parents=True,exist_ok=True)
    cats=sorted(coco["categories"],key=lambda c:c["id"])
    cid2yolo={c["id"]:i for i,c in enumerate(cats)}
    byid={im["id"]:im for im in coco["images"]}
    anns=defaultdict(list)
    for a in coco["annotations"]: anns[a["image_id"]].append(a)
    ni=nb=0
    for i in ids:
        im=byid[i]; src=src_lookup(im["file_name"])
        if src is None: continue
        uniq=im["file_name"].replace("/","__").replace("\\","__")
        shutil.copy(src, out_root/f"images/{split}/{uniq}")
        W,H=im["width"],im["height"]; lines=[]
        for a in anns.get(i,[]):
            cx,cy,w,h=coco_bbox_to_yolo(a["bbox"],W,H)
            lines.append(f"{cid2yolo[a['category_id']]} {cx:.6f} {cy:.6f} {w:.6f} {h:.6f}")
            nb+=1
        (out_root/f"labels/{split}/{Path(uniq).stem}.txt").write_text("\n".join(lines))
        ni+=1
    return ni,nb

def add_negatives(neg_paths, out_root, n_total, val_frac, seed=SEED):
    if not neg_paths: print("no negatives"); return
    negs=neg_paths[:]; random.Random(seed).shuffle(negs); negs=negs[:n_total]
    nval=round(n_total*val_frac)
    for split,chunk in (("val",negs[:nval]),("train",negs[nval:])):
        (out_root/f"images/{split}").mkdir(parents=True,exist_ok=True)
        (out_root/f"labels/{split}").mkdir(parents=True,exist_ok=True)
        for p in chunk:
            shutil.copy(p, out_root/f"images/{split}/{p.name}")
            (out_root/f"labels/{split}/{p.stem}.txt").write_text("")
    print(f"negatives: {len(negs)-nval} train, {nval} val")

def filter_coco_to_classes(coco, keep_names):
    keep_set=set(keep_names)
    id2name={c["id"]:c["name"] for c in coco["categories"]}
    new_cats=[{"id":i+1,"name":n} for i,n in enumerate(keep_names)]
    name2new={c["name"]:c["id"] for c in new_cats}
    new_anns=[]
    for a in coco["annotations"]:
        nm=id2name.get(a["category_id"])
        if nm in keep_set:
            b=dict(a); b["category_id"]=name2new[nm]; new_anns.append(b)
    imgs_with_ann={a["image_id"] for a in new_anns}
    new_imgs=[im for im in coco["images"] if im["id"] in imgs_with_ann]
    return {"images":new_imgs,"annotations":new_anns,"categories":new_cats}

if YOUR_COCO_JSON is None:
    for c in INPUT_ROOT.rglob("*.json"):
        try:
            d=json.loads(Path(c).read_text())
            if "annotations" in d and "categories" in d:
                YOUR_COCO_JSON=c; break
        except Exception: pass
print("YOUR_COCO_JSON =", YOUR_COCO_JSON)
assert YOUR_COCO_JSON, "Set YOUR_COCO_JSON in CELL 0."

your_coco=json.loads(Path(YOUR_COCO_JSON).read_text())
YOUR_NAMES=[c["name"] for c in sorted(your_coco["categories"],key=lambda c:c["id"])]
print(f"{len(YOUR_NAMES)} classes in file:",YOUR_NAMES)

if YOUR_IMG_ROOT is None: YOUR_IMG_ROOT=Path(YOUR_COCO_JSON).parent
IMG_BASE=Path(YOUR_IMG_ROOT).parent
your_src={}
for p in Path(YOUR_IMG_ROOT).rglob("*"):
    if p.suffix.lower() in (".jpg",".jpeg",".png",".bmp"):
        your_src[str(p.relative_to(IMG_BASE))]=p
print("your images found:",len(your_src))

_bidx=defaultdict(list)
for k,v in your_src.items(): _bidx[Path(k).name].append(v)
def resolve_your_image(fn):
    if fn in your_src: return your_src[fn]
    h=_bidx.get(Path(fn).name,[]); return h[0] if len(h)==1 else None

found=sum(1 for im in your_coco["images"] if resolve_your_image(im["file_name"]))
print(f"COCO resolvable: {found}/{len(your_coco['images'])}")
assert found>=len(your_coco["images"])*0.98

if NEG_IMG_ROOT is None:
    for r in (INPUT_ROOT.iterdir() if INPUT_ROOT.exists() else []):
        if any(k in r.name.lower() for k in ("neg","good","clean","ok","defect-free")):
            NEG_IMG_ROOT=r; break
neg_files=[p for p in Path(NEG_IMG_ROOT).rglob("*")
           if p.suffix.lower() in (".jpg",".jpeg",".png",".bmp")] if NEG_IMG_ROOT else []
print("negatives:",len(neg_files),"from",NEG_IMG_ROOT)

missing=[k for k in KEEP if k not in YOUR_NAMES]
assert not missing, f"KEEP names not in YOUR_NAMES: {missing}"
coco8 = filter_coco_to_classes(your_coco, KEEP)
NAMES8 = [c["name"] for c in sorted(coco8["categories"],key=lambda c:c["id"])]
id2n = {c["id"]:c["name"] for c in coco8["categories"]}
print(f"8-class: {len(coco8['images'])} images, {len(coco8['annotations'])} anns")
cc=Counter(a["category_id"] for a in coco8["annotations"])
for cid in sorted(cc): print(f"  {id2n[cid]:<22} {cc[cid]}")

cls_freq=Counter(a["category_id"] for a in coco8["annotations"])
img_cls=defaultdict(set)
for a in coco8["annotations"]: img_cls[a["image_id"]].add(a["category_id"])
strat=defaultdict(list)
for im in coco8["images"]:
    cls=img_cls.get(im["id"],set())
    key=min(cls,key=lambda c:cls_freq[c]) if cls else "__none__"
    strat[key].append(im["id"])
rng=random.Random(SEED); y_train=set(); y_val=set()
for k,ids in strat.items():
    ids=ids[:]; rng.shuffle(ids)
    nv=max(1,round(len(ids)*VAL_FRAC)) if len(ids)>1 else 0
    y_val|=set(ids[:nv]); y_train|=set(ids[nv:])
assert not (y_train & y_val)
print(f"train {len(y_train)} | val {len(y_val)}")
for c in sorted(cls_freq):
    ntr=sum(1 for a in coco8["annotations"] if a["category_id"]==c and a["image_id"] in y_train)
    nva=sum(1 for a in coco8["annotations"] if a["category_id"]==c and a["image_id"] in y_val)
    print(f"  {id2n[c]:<22} train {ntr:>3} val {nva:>3}")

import yaml
DATA=WORK/"yolo8"
# Idempotent rebuild (pcb-port-to-batch): TmpDisk=0, so every rebuild is ~1,750 small-file
# Lustre writes. Skip when the tree is already built; PCB_FORCE_REBUILD=1 to force.
if not (DATA/"data.yaml").exists() or os.environ.get("PCB_FORCE_REBUILD"):
    shutil.rmtree(DATA, ignore_errors=True)
    ysl=lambda n: resolve_your_image(n)
    print("pos train:",write_yolo_split(coco8,y_train,"train",DATA,ysl,NAMES8))
    print("pos val  :",write_yolo_split(coco8,y_val,  "val",  DATA,ysl,NAMES8))
    add_negatives(neg_files,DATA,N_NEG_TOTAL,VAL_FRAC)
    (DATA/"data.yaml").write_text(yaml.safe_dump(
        {"path":str(DATA),"train":"images/train","val":"images/val",
         "names":{i:n for i,n in enumerate(NAMES8)}},sort_keys=False))
    print("data.yaml written; classes:",NAMES8)
else:
    print("dataset already built at",DATA,"- skipping rebuild (PCB_FORCE_REBUILD=1 to force)")

for split in ["train","val"]:
    imgs=[p for p in (DATA/f"images/{split}").rglob("*") if p.suffix.lower() in (".jpg",".jpeg",".png",".bmp")]
    labs=list((DATA/f"labels/{split}").rglob("*.txt"))
    nonempty=[p for p in labs if p.read_text().strip()]
    print(f"[{split}] images={len(imgs)} labels={len(labs)} non-empty={len(nonempty)}")

# PORTED: `!pip install ultralytics` removed — provided by the venv (see PRAJNA_CONFIG.md §5).

from ultralytics import RTDETR
model = RTDETR(MODEL)
model.train(
    data=str(DATA/"data.yaml"),
    epochs=EPOCHS, imgsz=IMG_SIZE, batch=BATCH, patience=30,
    project=str(RUNS_ROOT), name="rtdetr8_640",
    device=devices(),
    hsv_h=0.015, hsv_s=0.7, hsv_v=0.4,
    degrees=15, shear=10, scale=0.5,
    fliplr=0.5, flipud=0.5, mosaic=1.0,
    lr0=0.0001,               # RT-DETR uses a lower LR than YOLO (AdamW-style)
    seed=SEED,
)
BEST = str(RUNS_ROOT/"rtdetr8_640/weights/best.pt")
print("best ->", BEST)

res = model.val(data=str(DATA/"data.yaml"), split="val")
print(f"\n=== RT-DETR 8-CLASS (640px, with negatives) ===")
print(f"mAP@0.5      {res.box.map50:.4f}")
print(f"mAP@0.5:0.95 {res.box.map:.4f}")
print(f"precision    {res.box.mp:.4f}")
print(f"recall       {res.box.mr:.4f}")
print("\nper-class mAP@0.5:")
for i,n in res.names.items():
    m=res.box.maps[i] if i<len(res.box.maps) else 0
    print(f"  {n:<22} {m:.3f}")
print("\nCompare against your YOLO baseline: 0.757 (single-run) / 0.76 ± 0.02 (CV)")